"""
GitHub integration helpers for the Code Review Coach.
Handles HMAC signature verification, PR diff fetching, and PR review posting.
All code runs in the Flask request thread; diff content is never executed.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import urllib.error
import urllib.request
from typing import Optional

from .engine import ReviewResult, result_to_dict

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"

_CAT_LABELS = {
    "secrets":                   "Exposed Secret",
    "unsafe_input":              "Unsafe Input",
    "error_handling":            "Error Handling",
    "likely_bug":                "Likely Bug",
    "weak_tests":                "Weak Tests",
    "logging_sensitive":         "Sensitive Logging",
    "dangerous_deserialization": "Dangerous Deserialization",
    "path_traversal":            "Path Traversal",
    "insecure_dependency":       "Insecure Dependency",
}


def verify_signature(payload_bytes: bytes, secret: str, signature_header: str) -> bool:
    """
    Verify a GitHub X-Hub-Signature-256 HMAC header.
    Returns True if the payload matches the secret, False otherwise.
    Uses hmac.compare_digest to prevent timing attacks.
    """
    if not signature_header or not signature_header.startswith("sha256="):
        return False
    expected = "sha256=" + hmac.new(
        secret.encode("utf-8"), payload_bytes, hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(expected, signature_header)


def fetch_pr_diff(owner: str, repo: str, pr_number: int, token: str) -> str:
    """
    Fetch the unified diff of a GitHub pull request.
    Returns the diff text (str). Raises urllib.error.HTTPError on failure.
    The diff is returned as raw text — never executed.
    """
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}"
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github.v3.diff",
            "Authorization": f"Bearer {token}",
            "User-Agent": "code-review-coach/1.0",
        },
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read().decode("utf-8", errors="replace")


def _build_review_body(result: ReviewResult) -> str:
    """Build the top-level PR review comment body."""
    s = result.summary
    lines = [
        f"## Code Review Coach — {s.recommendation}",
        "",
        s.recommendation_reason,
        "",
        f"**{s.total_findings} finding(s)**",
    ]
    if s.by_severity:
        sev_parts = ", ".join(f"{n} {sev}" for sev, n in s.by_severity.items() if n > 0)
        lines.append(f"Severity breakdown: {sev_parts}")
    if s.main_risks:
        lines.append("")
        lines.append("**Main risks:**")
        for r in s.main_risks:
            lines.append(f"- {r}")
    if s.next_steps:
        lines.append("")
        lines.append("**Next steps:**")
        for step in s.next_steps:
            lines.append(f"- {step}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by [Code Review Coach](https://github.com) — IBM Bob Hackathon*")
    return "\n".join(lines)


def _build_inline_comments(result: ReviewResult) -> list:
    """Build GitHub inline review comment objects for each finding that has a line number."""
    comments = []
    for f in result.findings:
        if not f.line_number:
            continue
        cat = _CAT_LABELS.get(f.category, f.category)
        body_lines = [
            f"**[{f.severity.upper()}] {cat}**",
            "",
            f.explanation,
            "",
            f"> **Recommended fix:** {f.recommended_fix}",
        ]
        if f.matched_text:
            body_lines += ["", f"Matched: `{f.matched_text[:100]}`"]
        comments.append({
            "path": f.filename,
            "line": f.line_number,
            "side": "RIGHT",
            "body": "\n".join(body_lines),
        })
    return comments


def post_review(
    owner: str,
    repo: str,
    pr_number: int,
    token: str,
    result: ReviewResult,
    commit_sha: Optional[str] = None,
) -> dict:
    """
    Post a PR review with inline comments to GitHub.
    Returns the parsed GitHub API response.
    Raises urllib.error.HTTPError on failure.
    """
    _REC_EVENT = {
        "REQUEST_CHANGES":    "REQUEST_CHANGES",
        "NEEDS_DISCUSSION":   "COMMENT",
        "APPROVE":            "APPROVE",
        "APPROVE_WITH_NOTES": "APPROVE",
    }
    event = _REC_EVENT.get(result.summary.recommendation, "COMMENT")

    payload: dict = {
        "body":     _build_review_body(result),
        "event":    event,
        "comments": _build_inline_comments(result),
    }
    if commit_sha:
        payload["commit_id"] = commit_sha

    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type":  "application/json",
            "Accept":        "application/vnd.github.v3+json",
            "Authorization": f"Bearer {token}",
            "User-Agent":    "code-review-coach/1.0",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())
